"""empty message

Revision ID: 5bee58f94bc6
Revises: 73d8072a5b12
Create Date: 2021-07-04 16:17:16.469316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bee58f94bc6'
down_revision = '73d8072a5b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.String(length=500), nullable=True))
    op.drop_column('venue', 'web_site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('web_site', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'website')
    # ### end Alembic commands ###
